version: '3.8'
services:
  prisma-db-push:
    container_name: prisma-db-push
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mongodb

  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    name: nest-db
